# vim:ft=ansible:
---
# This Playbook will install necessary toolkit for experiments 

- hosts: worker
  remote_user: ubuntu 
  tasks:
    - name: Launch redis-server
      shell: "redis-server &"
      async: 45
      poll: 0

    - name: Copy monitoring daemon
      copy: src=/home/ubuntu/avada-ML/monitor_daemon.py 
            dest=/home/ubuntu/ 
            mode=750

    - name: Copy monitoring daemon
      copy: src=/home/ubuntu/avada-ML/redis_to_file.py 
            dest=/home/ubuntu/ 
            mode=750

    - name: Flush local redis data
      shell: "redis-cli flushall"
      async: 45
      poll: 0
