# vim:ft=ansible:
---
# This Playbook will install necessary toolkit for experiments 

- hosts: all
  remote_user: ubuntu 
  tasks:
    - name: Launch redis-server
      shell: "redis-server &"

    - name: Git clone avada-ML
      git: repo=git@github.com:chapter09/avada-ML.git
